version: "3.8"
services:
  backend:
    build:
      context: ./
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - mongo
  redis:
    image: redis
    ports:
      - 6379:6379
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:5.0.18
    container_name: mongo
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mexpress
    env_file:
      - .env
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  
networks:
  url-shortener-network:
    driver: bridge